// Operator evaluator tests (audit issue-1/task-3.2).
//
// Three layers:
//   1. unit semantics — every operator's state effect asserted
//      directly (matrices, text state, counters);
//   2. tolerance/hostility — unbalanced constructs, unknown operators,
//      dash arrays that must never move the pen, dict keywords that
//      must never dispatch, LCG-fuzzed buffers evaluated twice for
//      determinism (the ASan/TSan runs of this suite are the
//      memory-safety proof);
//   3. the ±0.001 pt precision gate — golden vectors generated by
//      scripts/gen_evaluator_golden.py (an INDEPENDENT Python model
//      of ISO 32000-1 cl. 9; U-015 interprets "Adobe Acrobat
//      reference output" as this deterministic synthetic reference).

#include <cmath>
#include <cstdint>
#include <span>
#include <string>
#include <string_view>
#include <vector>

#include "../tests/test_harness.hpp"
#include "pdftoolkit/layout/evaluator.hpp"

#include "test_evaluator_golden.inc"

using pdftoolkit::layout::EvaluatorStats;
using pdftoolkit::layout::FontMetricsResolver;
using pdftoolkit::layout::GlyphPlacement;
using pdftoolkit::layout::GlyphSink;
using pdftoolkit::layout::Mat6;
using pdftoolkit::layout::OperatorEvaluator;
using pdftoolkit::layout::TextState;
using pdftoolkit::layout::kMat6Identity;
using pdftoolkit::layout::mat_mul;

namespace {

class CaptureSink final : public GlyphSink {
public:
    struct Record {
        std::uint32_t code;
        std::string font;  // COPIED: glyph font views die with the
                           // content buffer (the documented lifetime
                           // contract — tests must respect it)
        Mat6 trm;
        float advance_tx;
    };
    void on_glyph(const GlyphPlacement& g) noexcept override {
        records.push_back(
            Record{g.code, std::string(g.font), g.trm, g.advance_tx});
    }
    std::vector<Record> records;

    // View-compatible accessors so glyph-order assertions read
    // naturally.
    std::size_t size() const noexcept { return records.size(); }
    bool empty() const noexcept { return records.empty(); }
    const Record& operator[](std::size_t i) const noexcept {
        return records[i];
    }
};

// The resolver formulas the golden generator documents (must match
// scripts/gen_evaluator_golden.py exactly).
unsigned test_code_bytes(void*, std::string_view font) noexcept {
    if (font == "CID" || font == "WIDE") {
        return 2;
    }
    return 1;
}

std::uint32_t test_advance(void*, std::string_view font,
                           std::uint32_t code) noexcept {
    if (font == "CID") {
        return 300 + code % 900;
    }
    if (font == "WIDE") {
        return 500 + code % 300;
    }
    return 400 + code % 400;
}

FontMetricsResolver test_resolver() {
    FontMetricsResolver r;
    r.code_bytes = test_code_bytes;
    r.advance = test_advance;
    r.ctx = nullptr;
    return r;
}

std::vector<std::uint8_t> bytes_of(std::string_view text) {
    return std::vector<std::uint8_t>(text.begin(), text.end());
}

// A content buffer that OUTLIVES the evaluate() call — required
// whenever a test reads a string_view the evaluator holds (font
// names, sink events) after evaluation returns.
struct Script {
    std::vector<std::uint8_t> bytes;
    explicit Script(std::string_view text)
        : bytes(text.begin(), text.end()) {}
    void run(OperatorEvaluator& ev) { ev.evaluate(bytes); }
};

// For view-free assertions (matrices, counters) a temporary buffer
// is fine.
void eval_text(OperatorEvaluator& ev, std::string_view text) {
    const std::vector<std::uint8_t> bytes = bytes_of(text);
    ev.evaluate(bytes);
}

void assert_mat_close(const Mat6& actual, const double (&expected)[6],
                      double tol = 1e-3) {
    for (int i = 0; i < 6; ++i) {
        if (!(std::fabs(static_cast<double>(actual[static_cast<std::size_t>(
                              i)]) -
                        expected[i]) <= tol)) {
            throw std::runtime_error(
                std::string("matrix field ") + std::to_string(i) +
                " off: actual " + std::to_string(actual[static_cast<std::size_t>(i)]) +
                " expected " + std::to_string(expected[i]));
        }
    }
}

// --- 1. matrix helper -------------------------------------------------------

PDTK_TEST(mat_mul_matches_pdf_convention) {
    const Mat6 scale{2, 0, 0, 3, 0, 0};
    const Mat6 translate{1, 0, 0, 1, 10, 20};
    // Apply translate FIRST, then scale: the translation is scaled.
    const Mat6 a = mat_mul(translate, scale);
    PDTK_ASSERT(a[0] == 2.0F && a[3] == 3.0F);
    PDTK_ASSERT(a[4] == 20.0F && a[5] == 60.0F);
    // Apply scale FIRST, then translate: the translation survives raw.
    const Mat6 b = mat_mul(scale, translate);
    PDTK_ASSERT(b[4] == 10.0F && b[5] == 20.0F);
    // Identity is neutral on both sides.
    const Mat6 m{1, 2, 3, 4, 5, 6};
    const Mat6 l = mat_mul(kMat6Identity, m);
    const Mat6 r = mat_mul(m, kMat6Identity);
    for (int i = 0; i < 6; ++i) {
        PDTK_ASSERT(l[static_cast<std::size_t>(i)] == m[static_cast<std::size_t>(i)]);
        PDTK_ASSERT(r[static_cast<std::size_t>(i)] == m[static_cast<std::size_t>(i)]);
    }
}

// --- 2. operator unit semantics ----------------------------------------------

PDTK_TEST(bt_et_state_tracking) {
    OperatorEvaluator ev;
    PDTK_ASSERT(!ev.in_text_object());
    eval_text(ev, "BT");
    PDTK_ASSERT(ev.in_text_object());
    assert_mat_close(ev.text_line_matrix(), {1, 0, 0, 1, 0, 0});
    eval_text(ev, "ET");
    PDTK_ASSERT(!ev.in_text_object());
    // ET does not reset Tlm (it persists until the next BT — 9.4.1).
    eval_text(ev, "BT 100 200 Td ET");
    PDTK_ASSERT(ev.text_line_matrix()[4] == 100.0F);
    eval_text(ev, "BT");
    PDTK_ASSERT(ev.text_line_matrix()[4] == 0.0F);
}

PDTK_TEST(td_composes_into_line_matrix) {
    OperatorEvaluator ev;
    eval_text(ev, "BT 100 200 Td 10 20 Td");
    assert_mat_close(ev.text_line_matrix(), {1, 0, 0, 1, 110, 220});
}

PDTK_TEST(glyph_advance_never_moves_line_matrix) {
    // THE line-matrix subtlety: Tj advances Tm but not Tlm, so a
    // later Td(0,0) rewinds to the LINE start, not the pen.
    Script s("BT /F1 12 Tf 100 700 Td (Hello) Tj");
    CaptureSink sink;
    FontMetricsResolver r = test_resolver();
    OperatorEvaluator ev(&sink, r);
    s.run(ev);
    PDTK_ASSERT(sink.size() == 5);
    // The pen moved right...
    PDTK_ASSERT(ev.text_matrix()[4] > 100.0F);
    // ...but the line matrix did not.
    assert_mat_close(ev.text_line_matrix(), {1, 0, 0, 1, 100, 700});
    eval_text(ev, "0 0 Td");
    assert_mat_close(ev.text_matrix(), {1, 0, 0, 1, 100, 700});
}

PDTK_TEST(td_td_and_tstar_use_leading) {
    OperatorEvaluator ev;
    // TL is set first, then TD OVERWRITES it with -ty = 14 and
    // moves by (0,-14); T* adds another -14.
    eval_text(ev, "BT 10 TL 0 -14 TD T*");
    assert_mat_close(ev.text_line_matrix(), {1, 0, 0, 1, 0, -28});
    PDTK_ASSERT(ev.text_state().leading == 14.0F);
}

PDTK_TEST(tm_replaces_both_matrices) {
    Script s("BT /F1 12 Tf 100 100 Td 1 0 0 1 5 6 Tm (xx) Tj 0 0 Td");
    CaptureSink sink;
    FontMetricsResolver r = test_resolver();
    OperatorEvaluator ev(&sink, r);
    s.run(ev);
    assert_mat_close(ev.text_line_matrix(), {1, 0, 0, 1, 5, 6});
    assert_mat_close(ev.text_matrix(), {1, 0, 0, 1, 5, 6});
}

PDTK_TEST(tf_sets_font_and_size) {
    Script s("BT /F2 14.5 Tf");
    OperatorEvaluator ev;
    s.run(ev);
    PDTK_ASSERT(ev.text_state().font == "F2");
    PDTK_ASSERT(ev.text_state().font_size == 14.5F);
}

PDTK_TEST(text_state_operators) {
    OperatorEvaluator ev;
    eval_text(ev, "BT 2 Tc 4.5 Tw 50 Tz 13 TL 7 Ts 2 Tr");
    const TextState& st = ev.text_state();
    PDTK_ASSERT(st.char_spacing == 2.0F);
    PDTK_ASSERT(st.word_spacing == 4.5F);
    PDTK_ASSERT(st.h_scale_pct == 50.0F);
    PDTK_ASSERT(st.leading == 13.0F);
    PDTK_ASSERT(st.rise == 7.0F);
    PDTK_ASSERT(st.render_mode == 2);
}

PDTK_TEST(q_q_saves_ctm_and_text_state) {
    Script s1("2 0 0 2 10 20 cm q 0.5 0 0 0.5 0 0 cm /F9 9 Tf");
    CaptureSink sink;
    FontMetricsResolver r = test_resolver();
    OperatorEvaluator ev(&sink, r);
    s1.run(ev);
    // Inside the q: CTM = [0.5..] x [2..] = [1 0 0 1 10 20].
    assert_mat_close(ev.ctm(), {1, 0, 0, 1, 10, 20});
    PDTK_ASSERT(ev.text_state().font == "F9");
    Script s2("Q");
    s2.run(ev);
    // Q restored the pre-q CTM and the (fontless) text state.
    assert_mat_close(ev.ctm(), {2, 0, 0, 2, 10, 20});
    PDTK_ASSERT(ev.text_state().font.empty());
    // Tlm is text-object-scoped, never q/Q state:
    eval_text(ev, "BT 5 6 Td q Q");
    assert_mat_close(ev.text_line_matrix(), {1, 0, 0, 1, 5, 6});
}

PDTK_TEST(q_underflow_and_overflow) {
    OperatorEvaluator ev;
    eval_text(ev, "Q");
    PDTK_ASSERT_EQ(ev.stats().gstate_underflow, std::size_t{1});
    // 70 nested q's: the stack holds 64; frames 65..70 are refused
    // (counted), and 64 Q's still balance.
    std::string deep;
    for (int i = 0; i < 70; ++i) {
        deep += "q ";
    }
    for (int i = 0; i < 64; ++i) {
        deep += "Q ";
    }
    eval_text(ev, deep.c_str());
    PDTK_ASSERT_EQ(ev.stats().gstate_overflow, std::size_t{6});
    assert_mat_close(ev.ctm(), {1, 0, 0, 1, 0, 0});
}

PDTK_TEST(cm_premultiplies) {
    // CTM' = M x CTM (8.4.2): a later cm's translation lives in the
    // PRE-cm user space, so the earlier cm scales it.
    OperatorEvaluator ev;
    eval_text(ev, "2 0 0 2 0 0 cm 1 0 0 1 10 0 cm");
    // Scale first, then translate: the 10 is doubled.
    assert_mat_close(ev.ctm(), {2, 0, 0, 2, 20, 0});
    OperatorEvaluator ev2;
    eval_text(ev2, "1 0 0 1 10 0 cm 2 0 0 2 0 0 cm");
    // Translate first, then scale: the 10 survives raw.
    assert_mat_close(ev2.ctm(), {2, 0, 0, 2, 10, 0});
}

PDTK_TEST(quote_operator_is_tstar_plus_tj) {
    Script s("BT /F1 12 Tf 12 TL 100 700 Td (first) '");
    CaptureSink sink;
    FontMetricsResolver r = test_resolver();
    OperatorEvaluator ev(&sink, r);
    s.run(ev);
    PDTK_ASSERT_EQ(sink.size(), std::size_t{5});
    // T* moved the line to 700-12 = 688; first glyph sits there.
    PDTK_ASSERT(std::fabs(static_cast<double>(sink[0].trm[5]) -
                          688.0) < 1e-9);
}

PDTK_TEST(dquote_sets_spacing_then_shows) {
    Script s("BT /F1 12 Tf 12 TL 100 700 Td 3 2 (ab) \"");
    CaptureSink sink;
    FontMetricsResolver r = test_resolver();
    OperatorEvaluator ev(&sink, r);
    s.run(ev);
    PDTK_ASSERT_EQ(sink.size(), std::size_t{2});
    PDTK_ASSERT(ev.text_state().word_spacing == 3.0F);
    PDTK_ASSERT(ev.text_state().char_spacing == 2.0F);
    PDTK_ASSERT(std::fabs(static_cast<double>(sink[0].trm[5]) -
                          688.0) < 1e-9);
}

PDTK_TEST(tj_number_positive_moves_left) {
    Script s("BT /F1 12 Tf 100 700 Td [(A) 100 (B)] TJ");
    CaptureSink sink;
    FontMetricsResolver r = test_resolver();
    OperatorEvaluator ev(&sink, r);
    s.run(ev);
    PDTK_ASSERT_EQ(sink.size(), std::size_t{2});
    // A: w0 = 400 + 'A' % 400 = 465 -> 5.58 pt. Number 100 at Tfs 12
    // shifts left by 100/1000*12 = 1.2 pt.
    const double ax = sink[0].trm[4];
    const double bx = sink[1].trm[4];
    PDTK_ASSERT(std::fabs(bx - (ax + 5.58 - 1.2)) < 1e-3);
    PDTK_ASSERT_EQ(ev.stats().tj_arrays_replayed, std::size_t{1});
    PDTK_ASSERT_EQ(ev.stats().tj_number_adjustments, std::size_t{1});
}

PDTK_TEST(non_tj_array_never_moves_the_pen) {
    // The dash pattern `[3 2] 0 d` must not be mistaken for TJ
    // elements: displacement stays zero.
    Script s("BT /F1 12 Tf 100 700 Td [3 2] 0 d 0.5 w (x) Tj");
    CaptureSink sink;
    FontMetricsResolver r = test_resolver();
    OperatorEvaluator ev(&sink, r);
    s.run(ev);
    PDTK_ASSERT_EQ(sink.size(), std::size_t{1});
    PDTK_ASSERT(std::fabs(static_cast<double>(sink[0].trm[4]) -
                          100.0) < 1e-9);
    PDTK_ASSERT_EQ(ev.stats().tj_arrays_replayed, std::size_t{0});
    PDTK_ASSERT_EQ(ev.stats().ops_unknown, std::size_t{2});  // d, w
}

PDTK_TEST(nested_array_inside_tj_is_skipped) {
    Script s("BT /F1 12 Tf 100 700 Td [(a) [(b)] 50 (c)] TJ");
    CaptureSink sink;
    FontMetricsResolver r = test_resolver();
    OperatorEvaluator ev(&sink, r);
    s.run(ev);
    // Only a and c show; the nested array's members are skipped.
    PDTK_ASSERT_EQ(sink.size(), std::size_t{2});
    PDTK_ASSERT_EQ(sink[0].code, std::uint32_t{'a'});
    PDTK_ASSERT_EQ(sink[1].code, std::uint32_t{'c'});
}

PDTK_TEST(dict_keywords_never_dispatch) {
    // true / null / R inside a BDC property dict are VALUES, not
    // operators: no text state may change, no unknown-op drop of the
    // pending name may leak.
    Script s(
        "BT /F1 12 Tf 100 700 Td /P << /MCID 0 /Toggle true"
        " /Ref 4 0 R >> BDC EMC (ok) Tj");
    CaptureSink sink;
    FontMetricsResolver r = test_resolver();
    OperatorEvaluator ev(&sink, r);
    s.run(ev);
    PDTK_ASSERT_EQ(sink.size(), std::size_t{2});
    PDTK_ASSERT(std::fabs(static_cast<double>(sink[0].trm[4]) -
                          100.0) < 1e-9);
    // BDC and EMC are the only unknown operators.
    PDTK_ASSERT_EQ(ev.stats().ops_unknown, std::size_t{2});
}

PDTK_TEST(outside_bt_showing_and_positioning_are_ignored) {
    Script s("(ghost) Tj 100 200 Td [(x)] TJ 5 T* (more) '");
    CaptureSink sink;
    FontMetricsResolver r = test_resolver();
    OperatorEvaluator ev(&sink, r);
    s.run(ev);
    PDTK_ASSERT(sink.empty());
    PDTK_ASSERT_EQ(ev.stats().ops_outside_text, std::size_t{5});
    // Text STATE ops still apply outside text objects (9.3.1).
    eval_text(ev, "7 Tc");
    PDTK_ASSERT(ev.text_state().char_spacing == 7.0F);
}

PDTK_TEST(unknown_operators_drop_operands) {
    OperatorEvaluator ev;
    eval_text(ev,
              "1 0 0 RG /GS1 gs 72 700 m 300 700 l S [1 2 3] 0 d");
    PDTK_ASSERT_EQ(ev.stats().ops_unknown, std::size_t{6});
    PDTK_ASSERT_EQ(ev.stats().glyphs_emitted, std::size_t{0});
}

// --- 3. string decoding ------------------------------------------------------

PDTK_TEST(literal_string_escapes) {
    Script s(
        "BT /F1 12 Tf (a\\nb\\tb\\rb\\bb\\fb(b)b\\\\b"
        "\\101b\\7b\\zbb\\\ncc) Tj ET");
    CaptureSink sink;
    FontMetricsResolver r = test_resolver();
    OperatorEvaluator ev(&sink, r);
    s.run(ev);
    const std::vector<std::uint32_t> expected{
        'a', '\n', 'b', '\t', 'b', '\r', 'b', 0x08, 'b',
        0x0C, 'b', '(',  'b', ')',  'b', '\\', 'b', 'A',  // \101
        'b', 7,    'b', 'z',  'b',  'b',  'c',  'c',      // \7, \z, \\\n
    };
    PDTK_ASSERT_EQ(sink.size(), expected.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {
        PDTK_ASSERT_EQ(sink[i].code, expected[i]);
    }
}

PDTK_TEST(hex_string_decoding) {
    // Whitespace ignored; non-hex junk (Z, z) skipped; <9> pads a
    // low 0 -> 0x90.
    Script s("BT /F1 12 Tf <41 4243Zz> Tj <9> Tj ET");
    CaptureSink sink;
    FontMetricsResolver r = test_resolver();
    OperatorEvaluator ev(&sink, r);
    s.run(ev);
    const std::vector<std::uint32_t> expected{0x41, 0x42, 0x43, 0x90};
    PDTK_ASSERT_EQ(sink.size(), expected.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {
        PDTK_ASSERT_EQ(sink[i].code, expected[i]);
    }
}

PDTK_TEST(tw_applies_only_to_single_byte_space) {
    FontMetricsResolver r = test_resolver();
    // Single-byte font: the space gains Tw, letters do not.
    // w0('a') = 400 + 97 = 497 -> 4.97 pt at Tfs 10;
    // w0(' ') = 432 -> 4.32 + Tw 10 = 14.32 pt.
    {
        Script s("BT /F1 10 Tf 10 Tw (a a) Tj ET");
        CaptureSink sink;
        OperatorEvaluator ev(&sink, r);
        s.run(ev);
        PDTK_ASSERT_EQ(sink.size(), std::size_t{3});
        // advance_tx is a float32 field: one rounding is in-tolerance.
        PDTK_ASSERT(std::fabs(static_cast<double>(sink[0].advance_tx) -
                              4.97) < 1e-6);
        PDTK_ASSERT(std::fabs(static_cast<double>(sink[1].advance_tx) -
                              14.32) < 1e-6);
        PDTK_ASSERT(std::fabs(static_cast<double>(sink[2].advance_tx) -
                              4.97) < 1e-6);
    }
    // Two-byte font: the code 0x0020 is NOT a single-byte space —
    // w0(0x20) = 332 -> 3.32, w0(0x21) = 333 -> 3.33: no Tw jump.
    {
        Script s("BT /CID 10 Tf 10 Tw <0020 0021> Tj ET");
        CaptureSink sink;
        OperatorEvaluator ev(&sink, r);
        s.run(ev);
        PDTK_ASSERT_EQ(sink.size(), std::size_t{2});
        PDTK_ASSERT(std::fabs(static_cast<double>(sink[0].advance_tx) -
                              3.32) < 1e-6);
        PDTK_ASSERT(std::fabs(static_cast<double>(sink[1].advance_tx) -
                              3.33) < 1e-6);
    }
}

PDTK_TEST(two_byte_code_packing_and_odd_tail) {
    Script s("BT /CID 12 Tf <1234002001> Tj <12345> Tj ET");
    CaptureSink sink;
    FontMetricsResolver r = test_resolver();
    OperatorEvaluator ev(&sink, r);
    s.run(ev);
    PDTK_ASSERT_EQ(sink.size(), std::size_t{3});
    PDTK_ASSERT_EQ(sink[0].code, std::uint32_t{0x1234});
    PDTK_ASSERT_EQ(sink[1].code, std::uint32_t{0x0020});
    PDTK_ASSERT_EQ(sink[2].code, std::uint32_t{0x1234});
    // Both strings leave one odd trailing byte (01 and 5).
    PDTK_ASSERT_EQ(ev.stats().unterminated_code_tail, std::size_t{2});
}

PDTK_TEST(default_resolver_is_one_byte_and_1000) {
    Script s("BT /Whatever 10 Tf (AB) Tj ET");
    CaptureSink sink;
    OperatorEvaluator ev(&sink);
    s.run(ev);
    PDTK_ASSERT_EQ(sink.size(), std::size_t{2});
    // w0 = 1000 thousandths = 1 em x 10 pt (float field: 1e-6).
    PDTK_ASSERT(std::fabs(static_cast<double>(sink[0].advance_tx) -
                          10.0) < 1e-6);
}

// --- 4. tolerance & hostility --------------------------------------------------

PDTK_TEST(empty_and_separator_only_streams) {
    OperatorEvaluator ev;
    eval_text(ev, "");
    eval_text(ev, "   \n\t\f\r\0 ");
    eval_text(ev, "% just a comment\n%%");
    PDTK_ASSERT_EQ(ev.stats().ops_dispatched, std::size_t{0});
    PDTK_ASSERT(ev.stats().glyphs_emitted == 0);
}

PDTK_TEST(unterminated_constructs) {
    FontMetricsResolver r = test_resolver();
    // An unterminated literal string swallows the rest of the stream
    // (including any would-be Tj): the operand is held, no glyphs
    // are shown, nothing crashes (the tolerant contract).
    {
        Script s("BT /F1 12 Tf (unterminated");
        CaptureSink sink;
        OperatorEvaluator ev(&sink, r);
        s.run(ev);
        PDTK_ASSERT_EQ(sink.size(), std::size_t{0});
        PDTK_ASSERT_EQ(ev.stats().ops_dispatched, std::size_t{2});
        PDTK_ASSERT(ev.in_text_object());
    }
    {
        Script s("BT [ (a");
        CaptureSink sink;
        OperatorEvaluator ev(&sink, r);
        s.run(ev);
        PDTK_ASSERT_EQ(sink.size(), std::size_t{0});
    }
    {
        Script s("BT << /A ");
        OperatorEvaluator ev;
        s.run(ev);
        PDTK_ASSERT(ev.in_text_object());
    }
}

PDTK_TEST(stray_brackets_are_counted) {
    OperatorEvaluator ev;
    eval_text(ev, "] >> ] >>");
    PDTK_ASSERT_EQ(ev.stats().stray_array_ends, std::size_t{2});
    PDTK_ASSERT_EQ(ev.stats().stray_dict_ends, std::size_t{2});
}

PDTK_TEST(operand_accumulator_overflow_is_counted) {
    FontMetricsResolver r = test_resolver();
    OperatorEvaluator ev;
    // 10 numbers then an unknown op: only 8 fit.
    eval_text(ev, "1 2 3 4 5 6 7 8 9 10 bogus");
    PDTK_ASSERT_EQ(ev.stats().operand_overflows, std::size_t{2});
    // Two strings then Tj: only the first is kept, one more overflow.
    Script s("BT (a) (b) Tj");
    CaptureSink sink;
    OperatorEvaluator ev2(&sink, r);
    s.run(ev2);
    PDTK_ASSERT_EQ(ev2.stats().operand_overflows, std::size_t{1});
    PDTK_ASSERT_EQ(sink.size(), std::size_t{1});
}

PDTK_TEST(hostile_buffers_are_deterministic) {
    // LCG-fuzzed buffers, evaluated twice: identical glyph counts,
    // identical final matrices, and never a crash (the sanitizer
    // builds of this suite are the memory-safety proof).
    std::uint32_t state = 987654321u;
    const auto next_byte = [&state]() {
        state = state * 1664525u + 1013904223u;
        return static_cast<std::uint8_t>(state >> 13);
    };
    for (int round = 0; round < 200; ++round) {
        std::vector<std::uint8_t> buf;
        buf.resize(256 + static_cast<std::size_t>(round % 2000));
        for (auto& b : buf) {
            b = next_byte();
        }
        CaptureSink sink1;
        CaptureSink sink2;
        FontMetricsResolver r = test_resolver();
        OperatorEvaluator ev1(&sink1, r);
        OperatorEvaluator ev2(&sink2, r);
        ev1.evaluate(buf);
        ev2.evaluate(buf);
        PDTK_ASSERT_EQ(sink1.size(), sink2.size());
        PDTK_ASSERT_EQ(ev1.stats().glyphs_emitted,
                       ev2.stats().glyphs_emitted);
        PDTK_ASSERT_EQ(ev1.stats().ops_dispatched,
                       ev2.stats().ops_dispatched);
        const Mat6 m1 = ev1.text_matrix();
        const Mat6 m2 = ev2.text_matrix();
        for (int i = 0; i < 6; ++i) {
            PDTK_ASSERT(
                m1[static_cast<std::size_t>(i)] == m2[static_cast<std::size_t>(i)]);
        }
    }
}

PDTK_TEST(megabyte_junk_terminates) {
    std::vector<std::uint8_t> buf(1u << 20, 0xC1u);
    // Sprinkle structure to exercise every mode.
    const std::string pattern =
        "BT [(\\<<>>)] TJ << q Q cm 12 Tf (";
    for (std::size_t i = 0; i + pattern.size() < buf.size(); i += 997) {
        std::copy(pattern.begin(), pattern.end(),
                  buf.begin() + static_cast<std::ptrdiff_t>(i));
    }
    CaptureSink sink;
    FontMetricsResolver r = test_resolver();
    OperatorEvaluator ev(&sink, r);
    ev.evaluate(buf);
    PDTK_ASSERT_EQ(ev.stats().glyphs_emitted, sink.size());
}

PDTK_TEST(continuation_across_evaluate_calls) {
    // Operator-boundary split (the documented continuation rule:
    // state persists; operands must share a segment with their
    // operator).
    Script s1("BT /F1 12 Tf 100 700 Td (one) Tj ");
    Script s2("(two) Tj ET");
    CaptureSink sink;
    FontMetricsResolver r = test_resolver();
    OperatorEvaluator ev(&sink, r);
    s1.run(ev);
    PDTK_ASSERT_EQ(sink.size(), std::size_t{3});
    s2.run(ev);
    PDTK_ASSERT_EQ(sink.size(), std::size_t{6});
    PDTK_ASSERT(!ev.in_text_object());
    // reset() restarts cleanly.
    ev.reset();
    PDTK_ASSERT(!ev.in_text_object());
    PDTK_ASSERT_EQ(ev.stats().glyphs_emitted, std::size_t{0});
    assert_mat_close(ev.ctm(), {1, 0, 0, 1, 0, 0});
}

PDTK_TEST(cross_buffer_pending_array_is_dropped) {
    // An array completed in one buffer followed by TJ in a DIFFERENT
    // buffer: the recorded range is meaningless and must be dropped.
    Script s1("BT [(a) ");
    Script s2("] TJ");
    CaptureSink sink;
    FontMetricsResolver r = test_resolver();
    OperatorEvaluator ev(&sink, r);
    s1.run(ev);
    s2.run(ev);
    PDTK_ASSERT_EQ(sink.size(), std::size_t{0});
    PDTK_ASSERT_EQ(ev.stats().tj_arrays_replayed, std::size_t{0});
    // The array and its TJ must share one evaluate() call — the
    // documented continuation semantics.
}

PDTK_TEST(benchmark_of_state_stack_depth) {
    // 64-deep q/Q nesting round-trips exactly.
    std::string stream = "BT ";
    for (int i = 0; i < 64; ++i) {
        stream += "q 1 0 0 1 1 0 cm ";
    }
    for (int i = 0; i < 64; ++i) {
        stream += "Q ";
    }
    OperatorEvaluator ev;
    eval_text(ev, stream);
    PDTK_ASSERT_EQ(ev.stats().gstate_overflow, std::size_t{0});
    PDTK_ASSERT_EQ(ev.stats().gstate_underflow, std::size_t{0});
    assert_mat_close(ev.ctm(), {1, 0, 0, 1, 0, 0});
}

// --- 5. the ±0.001 pt golden gate ----------------------------------------------

PDTK_TEST(golden_gate_within_0_001_pt) {
    for (std::size_t s = 0; s < kGoldenScenarioCount; ++s) {
        const GoldenScenario& sc = kGoldenScenarios[s];
        CaptureSink sink;
        FontMetricsResolver r = test_resolver();
        OperatorEvaluator ev(&sink, r);
        const std::vector<std::uint8_t> bytes = bytes_of(sc.content);
        if (sc.split > 0) {
            ev.evaluate(std::span<const std::uint8_t>(
                bytes.data(), sc.split));
            ev.evaluate(std::span<const std::uint8_t>(
                bytes.data() + sc.split, bytes.size() - sc.split));
        } else {
            ev.evaluate(bytes);
        }

        if (sink.size() != sc.glyph_count) {
            throw std::runtime_error(
                std::string(sc.name) + ": glyph count " +
                std::to_string(sink.size()) + " != expected " +
                std::to_string(sc.glyph_count));
        }
        for (std::size_t i = 0; i < sc.glyph_count; ++i) {
            const GoldenGlyph& want = kGoldenGlyphs[sc.first_glyph + i];
            const auto& got = sink[i];
            if (got.code != want.code) {
                throw std::runtime_error(
                    std::string(sc.name) + ": glyph " + std::to_string(i) +
                    " code mismatch");
            }
            if (got.font != std::string_view(want.font)) {
                throw std::runtime_error(
                    std::string(sc.name) + ": glyph " + std::to_string(i) +
                    " font mismatch");
            }
            for (int k = 0; k < 6; ++k) {
                const double actual = got.trm[static_cast<std::size_t>(k)];
                const double expected = want.trm[k];
                if (!(std::fabs(actual - expected) <= 1e-3)) {
                    throw std::runtime_error(
                        std::string(sc.name) + ": glyph " +
                        std::to_string(i) + " trm[" + std::to_string(k) +
                        "] actual " + std::to_string(actual) +
                        " vs golden " + std::to_string(expected));
                }
            }
            if (!(std::fabs(static_cast<double>(got.advance_tx) -
                            want.advance) <= 1e-3)) {
                throw std::runtime_error(
                    std::string(sc.name) + ": glyph " + std::to_string(i) +
                    " advance mismatch");
            }
        }
        assert_mat_close(ev.ctm(), sc.final_ctm);
        assert_mat_close(ev.text_line_matrix(), sc.final_tlm);
        assert_mat_close(ev.text_matrix(), sc.final_tm);
    }
}

}  // namespace

PDTK_TEST_MAIN()
